In [1]:
import pandas as pd

df = pd.read_csv("cleaned_model_ready.csv")
df.head()

,part_id,part_name,year_month,year,month,product_category,product_type,hsn_number,target_demand_qty,purchase_qty,...,demand_lag_12m,demand_rolling_3m_avg,demand_rolling_6m_avg,demand_std_3m,sales_revenue_lag_1m,n_sales_invoices_lag_1m,service_qty_lag_1m,service_revenue_lag_1m,purchase_qty_lag_1m,months_since_last_demand
0,-1.731684,-1.371834,2023-12-01,-2.190890,1.616338,-0.191127,0.025227,0.431611,-0.06622,-0.041395,...,-0.005935,-0.007725,-0.007814,-0.004867,-0.010684,-0.014060,-0.007831,-0.006174,-0.005310,0.056565
1,-1.731684,-1.371834,2024-01-01,-0.867227,-1.416672,-0.191127,0.025227,0.431611,-0.06622,-0.041395,...,-0.005935,-0.070796,-0.072054,-0.004867,-0.103271,-0.148548,-0.070568,-0.051266,-0.042213,0.056565
2,-1.731684,-1.371834,2024-02-01,-0.867227,-1.140944,-0.191127,0.025227,0.431611,-0.06622,-0.041395,...,-0.005935,-0.070796,-0.072054,-0.065728,-0.103271,-0.148548,-0.070568,-0.051266,-0.042213,0.056565
3,-1.731684,-1.371834,2024-03-01,-0.867227,-0.865216,-0.191127,0.025227,0.431611,-0.06622,-0.041395,...,-0.005935,-0.070796,-0.072054,-0.065728,-0.103271,-0.148548,-0.070568,-0.051266,-0.042213,0.056565
4,-1.731684,-1.371834,2024-04-01,-0.867227,-0.589488,-0.191127,0.025227,0.431611,-0.06622,-0.041395,...,-0.005935,-0.070796,-0.072054,-0.065728,-0.103271,-0.148548,-0.070568,-0.051266,-0.042213,0.056565

In [2]:
df['sales_to_demand_ratio'] = df['sales_qty'] / df['target_demand_qty']

df[['sales_qty','target_demand_qty','sales_to_demand_ratio']].head()

   sales_qty  target_demand_qty  sales_to_demand_ratio
0  -0.022368           -0.06622               0.337785
1  -0.022368           -0.06622               0.337785
2  -0.022368           -0.06622               0.337785
3  -0.022368           -0.06622               0.337785
4  -0.022368           -0.06622               0.337785

In [3]:
df['sales_lag_1m'] = df['sales_qty'].shift(1)
df['sales_lag_2m'] = df['sales_qty'].shift(2)

df[['sales_qty','sales_lag_1m','sales_lag_2m']].head(10)

   sales_qty  sales_lag_1m  sales_lag_2m
0  -0.022368           NaN           NaN
1  -0.022368     -0.022368           NaN
2  -0.022368     -0.022368     -0.022368
3  -0.022368     -0.022368     -0.022368
4  -0.022368     -0.022368     -0.022368
5  -0.022368     -0.022368     -0.022368
6  -0.022368     -0.022368     -0.022368
7  -0.022368     -0.022368     -0.022368
8  -0.022368     -0.022368     -0.022368
9  -0.022368     -0.022368     -0.022368

In [4]:
df['rolling_3m_sales'] = df['sales_qty'].rolling(window=3).mean()
df['rolling_3m_demand'] = df['target_demand_qty'].rolling(window=3).mean()
df[['sales_qty','rolling_3m_sales','target_demand_qty','rolling_3m_demand']].head(10)

   sales_qty  rolling_3m_sales  target_demand_qty  rolling_3m_demand
0  -0.022368               NaN           -0.06622                NaN
1  -0.022368               NaN           -0.06622                NaN
2  -0.022368         -0.022368           -0.06622           -0.06622
3  -0.022368         -0.022368           -0.06622           -0.06622
4  -0.022368         -0.022368           -0.06622           -0.06622
5  -0.022368         -0.022368           -0.06622           -0.06622
6  -0.022368         -0.022368           -0.06622           -0.06622
7  -0.022368         -0.022368           -0.06622           -0.06622
8  -0.022368         -0.022368           -0.06622           -0.06622
9  -0.022368         -0.022368           -0.06622           -0.06622

In [6]:
df['supplier_activity'] = df['n_suppliers'] * df['service_qty']

df[['n_suppliers','service_qty','supplier_activity']].head()

   n_suppliers  service_qty  supplier_activity
0    -0.372557    -0.069174           0.025771
1    -0.372557    -0.069174           0.025771
2    -0.372557    -0.069174           0.025771
3    -0.372557    -0.069174           0.025771
4    -0.372557    -0.069174           0.025771

In [7]:

df.to_csv("feature_engineered_dataset.csv", index=False)